import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "react-phone-input-2/lib/style.css";
import "./globals.scss";
import Provider from "#/components/provider";

// import Provider from "#/components/provider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
